from django.core.management.base import BaseCommand
from user.models import Category, Product
from django.utils import timezone
import random


class Command(BaseCommand):
    help = 'Add 30 products in each category'

    def handle(self, *args, **kwargs):
        # Define products for each category
        products_data = {
            'Vegetable': [
                {'name': 'Fresh Tomato', 'price': 45.00, 'original_price': 55.00, 'description': 'Fresh and organic tomatoes directly from farm. Perfect for salads, cooking, and curries.', 'tags': 'VEGETABLE,ORGANIC,FARM FRESH'},
                {'name': 'Green Chili', 'price': 80.00, 'original_price': 100.00, 'description': 'Spicy green chilies perfect for adding heat to your dishes. Freshly harvested.', 'tags': 'VEGETABLE,SPICY,ORGANIC'},
                {'name': 'Potato', 'price': 35.00, 'original_price': 45.00, 'description': 'Premium quality potatoes, versatile for all cooking needs. Fresh and firm.', 'tags': 'VEGETABLE,STAPLE,ORGANIC'},
                {'name': 'Onion', 'price': 40.00, 'original_price': 50.00, 'description': 'Fresh red onions perfect for cooking. Rich in flavor and nutrients.', 'tags': 'VEGETABLE,ESSENTIAL,ORGANIC'},
                {'name': 'Carrot', 'price': 50.00, 'original_price': 60.00, 'description': 'Sweet and crunchy carrots, great for salads and juices. Rich in vitamin A.', 'tags': 'VEGETABLE,HEALTHY,ORGANIC'},
                {'name': 'Cabbage', 'price': 30.00, 'original_price': 40.00, 'description': 'Fresh green cabbage perfect for salads, stir-fry, and pickles.', 'tags': 'VEGETABLE,CRUNCHY,ORGANIC'},
                {'name': 'Cauliflower', 'price': 45.00, 'original_price': 55.00, 'description': 'White and fresh cauliflower, great for curries and snacks.', 'tags': 'VEGETABLE,LOW CALORIE,ORGANIC'},
                {'name': 'Spinach', 'price': 25.00, 'original_price': 35.00, 'description': 'Fresh green spinach leaves, rich in iron and vitamins.', 'tags': 'VEGETABLE,LEAFY GREEN,ORGANIC'},
                {'name': 'Brinjal', 'price': 38.00, 'original_price': 48.00, 'description': 'Fresh purple brinjals perfect for curries and baingan bharta.', 'tags': 'VEGETABLE,VERSITILE,ORGANIC'},
                {'name': 'Cucumber', 'price': 28.00, 'original_price': 35.00, 'description': 'Fresh and crunchy cucumbers, perfect for salads and raita.', 'tags': 'VEGETABLE,REFRESHING,ORGANIC'},
                {'name': 'Bell Pepper', 'price': 120.00, 'original_price': 150.00, 'description': 'Colorful bell peppers - red, green, and yellow. Great for stir-fries.', 'tags': 'VEGETABLE,COLORFUL,ORGANIC'},
                {'name': 'Broccoli', 'price': 85.00, 'original_price': 100.00, 'description': 'Fresh broccoli crowns, rich in nutrients and antioxidants.', 'tags': 'VEGETABLE,SUPERFOOD,ORGANIC'},
                {'name': 'Mushroom', 'price': 150.00, 'original_price': 180.00, 'description': 'Fresh button mushrooms, perfect for pizzas and curries.', 'tags': 'VEGETABLE,PROTEIN,ORGANIC'},
                {'name': 'Corn', 'price': 35.00, 'original_price': 45.00, 'description': 'Sweet corn cobs, great for boiling, grilling, or salads.', 'tags': 'VEGETABLE,SWEET,ORGANIC'},
                {'name': 'Green Peas', 'price': 70.00, 'original_price': 85.00, 'description': 'Fresh green peas, sweet and nutritious. Great for pulav and curries.', 'tags': 'VEGETABLE,PROTEIN,ORGANIC'},
                {'name': 'Okra', 'price': 55.00, 'original_price': 70.00, 'description': 'Fresh okra Lady Finger, perfect for bhindi masala.', 'tags': 'VEGETABLE,STAPLE,ORGANIC'},
                {'name': 'Bottle Gourd', 'price': 32.00, 'original_price': 42.00, 'description': 'Fresh bottle gourd (lauki), great for juice and curries.', 'tags': 'VEGETABLE,HEALTHY,ORGANIC'},
                {'name': 'Bitter Gourd', 'price': 48.00, 'original_price': 60.00, 'description': 'Fresh bitter gourd (karela), known for its health benefits.', 'tags': 'VEGETABLE,MEDICINAL,ORGANIC'},
                {'name': 'Radish', 'price': 25.00, 'original_price': 32.00, 'description': 'White radish (mooli), crispy and perfect for salads.', 'tags': 'VEGETABLE,CRUNCHY,ORGANIC'},
                {'name': 'Ginger', 'price': 120.00, 'original_price': 150.00, 'description': 'Fresh ginger roots, essential for Indian cooking.', 'tags': 'VEGETABLE,SPICE,ORGANIC'},
                {'name': 'Garlic', 'price': 90.00, 'original_price': 110.00, 'description': 'Fresh garlic bulbs, rich in flavor and medicinal properties.', 'tags': 'VEGETABLE,ESSENTIAL,ORGANIC'},
                {'name': 'Celery', 'price': 65.00, 'original_price': 80.00, 'description': 'Fresh celery stalks, great for soups and salads.', 'tags': 'VEGETABLE,HEALTHY,ORGANIC'},
                {'name': 'Coriander', 'price': 20.00, 'original_price': 30.00, 'description': 'Fresh coriander leaves, essential garnish for Indian dishes.', 'tags': 'VEGETABLE,HERB,ORGANIC'},
                {'name': 'Mint', 'price': 22.00, 'original_price': 30.00, 'description': 'Fresh mint leaves (pudina), perfect for chutneys and drinks.', 'tags': 'VEGETABLE,HERB,ORGANIC'},
                {'name': 'Lemon', 'price': 80.00, 'original_price': 100.00, 'description': 'Fresh yellow lemons, rich in vitamin C.', 'tags': 'VEGETABLE,CITRUS,ORGANIC'},
                {'name': 'Pumpkin', 'price': 28.00, 'original_price': 38.00, 'description': 'Fresh pumpkin, great for curries and sweets.', 'tags': 'VEGETABLE,NUTRITIOUS,ORGANIC'},
                {'name': 'Sweet Potato', 'price': 42.00, 'original_price': 52.00, 'description': 'Fresh sweet potatoes, healthy and delicious.', 'tags': 'VEGETABLE,HEALTHY,ORGANIC'},
                {'name': 'Turnip', 'price': 38.00, 'original_price': 48.00, 'description': 'Fresh turnips, great for salads and curries.', 'tags': 'VEGETABLE,ROOT,ORGANIC'},
                {'name': 'Beetroot', 'price': 45.00, 'original_price': 55.00, 'description': 'Fresh beetroots, rich in iron and antioxidants.', 'tags': 'VEGETABLE,HEALTHY,ORGANIC'},
                {'name': 'Green Beans', 'price': 55.00, 'original_price': 70.00, 'description': 'Fresh green beans, crispy and nutritious.', 'tags': 'VEGETABLE,PROTEIN,ORGANIC'},
            ],
            'fruits': [
                {'name': 'Apple', 'price': 180.00, 'original_price': 220.00, 'description': 'Fresh and juicy apples from Himalayan orchards. Rich in fiber and vitamins.', 'tags': 'FRUITS,ORGANIC,PREMIUM'},
                {'name': 'Banana', 'price': 50.00, 'original_price': 60.00, 'description': 'Fresh yellow bananas, great for energy and smoothies.', 'tags': 'FRUITS,ENERGY,ORGANIC'},
                {'name': 'Orange', 'price': 120.00, 'original_price': 150.00, 'description': 'Juicy oranges rich in vitamin C. Perfect for fresh juice.', 'tags': 'FRUITS,CITRUS,ORGANIC'},
                {'name': 'Mango', 'price': 200.00, 'original_price': 250.00, 'description': 'Sweet and juicy alphonso mangoes, the king of fruits.', 'tags': 'FRUITS,PREMIUM,SEASONAL'},
                {'name': 'Grapes', 'price': 150.00, 'original_price': 180.00, 'description': 'Fresh green and black grapes, seedless and sweet.', 'tags': 'FRUITS,ANTIOXIDANT,ORGANIC'},
                {'name': 'Pomegranate', 'price': 180.00, 'original_price': 220.00, 'description': 'Fresh pomegranates with juicy ruby seeds. Rich in antioxidants.', 'tags': 'FRUITS,HEALTHY,ORGANIC'},
                {'name': 'Papaya', 'price': 60.00, 'original_price': 75.00, 'description': 'Fresh papaya, great for digestion and skin health.', 'tags': 'FRUITS,HEALTHY,ORGANIC'},
                {'name': 'Watermelon', 'price': 40.00, 'original_price': 50.00, 'description': 'Fresh watermelons, perfect for summer hydration.', 'tags': 'FRUITS,REFRESHING,SEASONAL'},
                {'name': 'Pineapple', 'price': 70.00, 'original_price': 85.00, 'description': 'Sweet and tangy pineapples, great for juices.', 'tags': 'FRUITS,TROPICAL,ORGANIC'},
                {'name': 'Guava', 'price': 55.00, 'original_price': 70.00, 'description': 'Fresh pink guavas, rich in vitamin C and fiber.', 'tags': 'FRUITS,HEALTHY,ORGANIC'},
                {'name': 'Chikoo', 'price': 80.00, 'original_price': 100.00, 'description': 'Sweet chikoos (sapodilla), creamy and delicious.', 'tags': 'FRUITS,TROPICAL,ORGANIC'},
                {'name': 'Coconut', 'price': 45.00, 'original_price': 55.00, 'description': 'Fresh coconuts with sweet water and flesh.', 'tags': 'FRUITS,TROPICAL,ORGANIC'},
                {'name': 'Lychee', 'price': 200.00, 'original_price': 250.00, 'description': 'Juicy lychees from Assam, sweet and fragrant.', 'tags': 'FRUITS,PREMIUM,SEASONAL'},
                {'name': 'Dragon Fruit', 'price': 180.00, 'original_price': 220.00, 'description': 'Exotic dragon fruit, rich in antioxidants.', 'tags': 'FRUITS,EXOTIC,ORGANIC'},
                {'name': 'Avocado', 'price': 250.00, 'original_price': 300.00, 'description': 'Creamy avocados, perfect for guacamole and smoothies.', 'tags': 'FRUITS,HEALTHY,ORGANIC'},
                {'name': 'Kiwi', 'price': 150.00, 'original_price': 180.00, 'description': 'Fresh kiwis, rich in vitamin C and fiber.', 'tags': 'FRUITS,IMPORTED,ORGANIC'},
                {'name': 'Strawberry', 'price': 250.00, 'original_price': 300.00, 'description': 'Fresh strawberries, sweet and juicy.', 'tags': 'FRUITS,PREMIUM,SEASONAL'},
                {'name': 'Blueberry', 'price': 350.00, 'original_price': 400.00, 'description': 'Premium blueberries, rich in antioxidants.', 'tags': 'FRUITS,SUPERFOOD,ORGANIC'},
                {'name': 'Cherry', 'price': 400.00, 'original_price': 480.00, 'description': 'Fresh red cherries, sweet and juicy.', 'tags': 'FRUITS,PREMIUM,SEASONAL'},
                {'name': 'Peach', 'price': 180.00, 'original_price': 220.00, 'description': 'Fresh peaches with fuzzy skin and sweet flesh.', 'tags': 'FRUITS,SEASONAL,ORGANIC'},
                {'name': 'Pear', 'price': 150.00, 'original_price': 180.00, 'description': 'Fresh pears, sweet and crunchy.', 'tags': 'FRUITS,HEALTHY,ORGANIC'},
                {'name': 'Plum', 'price': 200.00, 'original_price': 240.00, 'description': 'Fresh plums, sweet and tangy.', 'tags': 'FRUITS,SEASONAL,ORGANIC'},
                {'name': 'Apricot', 'price': 250.00, 'original_price': 300.00, 'description': 'Fresh apricots, rich in vitamins.', 'tags': 'FRUITS,HEALTHY,ORGANIC'},
                {'name': 'Fig', 'price': 300.00, 'original_price': 360.00, 'description': 'Fresh figs, sweet and nutritious.', 'tags': 'FRUITS,SUPERFOOD,ORGANIC'},
                {'name': 'Jackfruit', 'price': 80.00, 'original_price': 100.00, 'description': 'Fresh jackfruit, unique flavor and texture.', 'tags': 'FRUITS,TROPICAL,ORGANIC'},
                {'name': 'Custard Apple', 'price': 120.00, 'original_price': 150.00, 'description': 'Sweet custard apples with creamy flesh.', 'tags': 'FRUITS,CREAMY,ORGANIC'},
                {'name': 'Muskmelon', 'price': 45.00, 'original_price': 55.00, 'description': 'Fresh muskmelon, sweet and fragrant.', 'tags': 'FRUITS,REFRESHING,SEASONAL'},
                {'name': 'Mosambi', 'price': 70.00, 'original_price': 85.00, 'description': 'Sweet lime (mosambi), perfect for juice.', 'tags': 'FRUITS,CITRUS,ORGANIC'},
                {'name': 'Grapefruit', 'price': 130.00, 'original_price': 160.00, 'description': 'Fresh grapefruit, tangy and healthy.', 'tags': 'FRUITS,CITRUS,ORGANIC'},
            ],
            'Cereals & Millets': [
                {'name': 'Basmati Rice', 'price': 180.00, 'original_price': 220.00, 'description': 'Premium quality basmati rice, long grains and aromatic.', 'tags': 'RICE,STAPLE,ORGANIC'},
                {'name': 'Brown Rice', 'price': 120.00, 'original_price': 150.00, 'description': 'Nutritious brown rice, rich in fiber and minerals.', 'tags': 'RICE,HEALTHY,ORGANIC'},
                {'name': 'Wheat', 'price': 45.00, 'original_price': 55.00, 'description': 'Fresh wheat grains, perfect for making flour.', 'tags': 'WHEAT,STAPLE,ORGANIC'},
                {'name': 'Bajra', 'price': 80.00, 'original_price': 100.00, 'description': 'Pearl millet (bajra), rich in protein and iron.', 'tags': 'MILLET,HEALTHY,ORGANIC'},
                {'name': 'Jowar', 'price': 75.00, 'original_price': 95.00, 'description': 'Sorghum (jowar), gluten-free and nutritious.', 'tags': 'MILLET,GLUTEN FREE,ORGANIC'},
                {'name': 'Ragi', 'price': 90.00, 'original_price': 110.00, 'description': 'Finger millet (ragi), rich in calcium and iron.', 'tags': 'MILLET,SUPERFOOD,ORGANIC'},
                {'name': 'Kangni', 'price': 85.00, 'original_price': 105.00, 'description': 'Fox tail millet (kangni), lightweight and nutritious.', 'tags': 'MILLET,HEALTHY,ORGANIC'},
                {'name': 'Kutki', 'price': 95.00, 'original_price': 115.00, 'description': 'Little millet (kutki), easy to digest.', 'tags': 'MILLET,HEALTHY,ORGANIC'},
                {'name': 'Proso Millet', 'price': 88.00, 'original_price': 108.00, 'description': 'Proso millet, good source of energy.', 'tags': 'MILLET,ENERGY,ORGANIC'},
                {'name': 'Barnyard Millet', 'price': 92.00, 'original_price': 112.00, 'description': 'Sanwa millet, fast cooking and nutritious.', 'tags': 'MILLET,QUICK COOK,ORGANIC'},
                {'name': 'Oats', 'price': 120.00, 'original_price': 150.00, 'description': 'Rolled oats, perfect for breakfast.', 'tags': 'CEREAL,BREAKFAST,ORGANIC'},
                {'name': 'Quinoa', 'price': 250.00, 'original_price': 300.00, 'description': 'Premium quinoa, complete protein source.', 'tags': 'CEREAL,SUPERFOOD,ORGANIC'},
                {'name': 'Barley', 'price': 70.00, 'original_price': 85.00, 'description': 'Whole barley grains, rich in fiber.', 'tags': 'CEREAL,HEALTHY,ORGANIC'},
                {'name': 'Corn Flakes', 'price': 150.00, 'original_price': 180.00, 'description': 'Crispy corn flakes for healthy breakfast.', 'tags': 'CEREAL,BREAKFAST,ORGANIC'},
                {'name': 'Muesli', 'price': 200.00, 'original_price': 240.00, 'description': 'Healthy muesli with nuts and dried fruits.', 'tags': 'CEREAL,BREAKFAST,ORGANIC'},
                {'name': 'Wheat Flour', 'price': 55.00, 'original_price': 70.00, 'description': 'Whole wheat flour (atta) for chapatis.', 'tags': 'FLOUR,STAPLE,ORGANIC'},
                {'name': 'Rice Flour', 'price': 60.00, 'original_price': 75.00, 'description': 'Fine rice flour for snacks.', 'tags': 'FLOUR,GLUTEN FREE,ORGANIC'},
                {'name': 'Bajra Flour', 'price': 65.00, 'original_price': 80.00, 'description': 'Pearl millet flour for rotis.', 'tags': 'FLOUR,MILLET,ORGANIC'},
                {'name': 'Ragi Flour', 'price': 75.00, 'original_price': 90.00, 'description': 'Finger millet flour for healthy recipes.', 'tags': 'FLOUR,SUPERFOOD,ORGANIC'},
                {'name': 'Jowar Flour', 'price': 70.00, 'original_price': 85.00, 'description': 'Sorghum flour for gluten-free baking.', 'tags': 'FLOUR,GLUTEN FREE,ORGANIC'},
                {'name': 'Broken Wheat', 'price': 50.00, 'original_price': 60.00, 'description': 'Dalia broken wheat for upma and porridge.', 'tags': 'WHEAT,BREAKFAST,ORGANIC'},
                {'name': 'Semolina', 'price': 45.00, 'original_price': 55.00, 'description': 'Fine semolina (sooji) for upma and halwa.', 'tags': 'CEREAL,STAPLE,ORGANIC'},
                {'name': 'Vermicelli', 'price': 55.00, 'original_price': 65.00, 'description': 'Roasted vermicelli (seviyan) for desserts.', 'tags': 'CEREAL,DESSERT,ORGANIC'},
                {'name': 'Poha', 'price': 60.00, 'original_price': 75.00, 'description': 'Flattened rice (poha) for breakfast.', 'tags': 'RICE,BREAKFAST,ORGANIC'},
                {'name': 'Murru', 'price': 48.00, 'original_price': 58.00, 'description': 'Rice flakes (murru) for snacks.', 'tags': 'RICE,SNACK,ORGANIC'},
                {'name': 'Chiwda', 'price': 120.00, 'original_price': 150.00, 'description': 'Beaten rice (chiwda) for snacks.', 'tags': 'RICE,SNACK,ORGANIC'},
                {'name': 'Makhana', 'price': 350.00, 'original_price': 420.00, 'description': 'Fox nuts (makhana) for fasting.', 'tags': 'MILLET,SNACK,ORGANIC'},
                {'name': 'Bulgur Wheat', 'price': 80.00, 'original_price': 100.00, 'description': 'Couscous/bulgur for salads and pilaf.', 'tags': 'WHEAT,HEALTHY,ORGANIC'},
                {'name': 'Amaranth', 'price': 150.00, 'original_price': 180.00, 'description': 'Amaranth grains, ancient superfood.', 'tags': 'CEREAL,SUPERFOOD,ORGANIC'},
            ],
            'Pulses & Lentils': [
                {'name': 'Chana Dal', 'price': 120.00, 'original_price': 150.00, 'description': 'Split chickpeas (chana dal), protein-rich.', 'tags': 'PULSES,PROTEIN,ORGANIC'},
                {'name': 'Toor Dal', 'price': 150.00, 'original_price': 180.00, 'description': 'Pigeon pea lentils (toor dal), staple food.', 'tags': 'PULSES,STAPLE,ORGANIC'},
                {'name': 'Moong Dal', 'price': 140.00, 'original_price': 170.00, 'description': 'Green gram dal, easy to digest.', 'tags': 'PULSES,PROTEIN,ORGANIC'},
                {'name': 'Urad Dal', 'price': 130.00, 'original_price': 160.00, 'description': 'Black gram dal (urad), for curries and dosa.', 'tags': 'PULSES,PROTEIN,ORGANIC'},
                {'name': 'Masoor Dal', 'price': 110.00, 'original_price': 135.00, 'description': 'Red lentils (masoor), quick cooking.', 'tags': 'PULSES,PROTEIN,ORGANIC'},
                {'name': 'Rajma', 'price': 160.00, 'original_price': 200.00, 'description': 'Kidney beans (rajma), protein-rich.', 'tags': 'PULSES,PROTEIN,ORGANIC'},
                {'name': 'Chole', 'price': 150.00, 'original_price': 180.00, 'description': 'White chickpeas (chole), for chole bhature.', 'tags': 'PULSES,PROTEIN,ORGANIC'},
                {'name': 'Lobia', 'price': 130.00, 'original_price': 160.00, 'description': 'Black-eyed peas (lobia), nutritious.', 'tags': 'PULSES,PROTEIN,ORGANIC'},
                {'name': 'Mattar', 'price': 120.00, 'original_price': 150.00, 'description': 'Green peas (mattar), for pulav.', 'tags': 'PULSES,VEGETABLE,ORGANIC'},
                {'name': 'Soybeans', 'price': 100.00, 'original_price': 125.00, 'description': 'Whole soybeans, plant protein.', 'tags': 'PULSES,PROTEIN,ORGANIC'},
                {'name': 'Kala Chana', 'price': 140.00, 'original_price': 170.00, 'description': 'Black chickpeas, rich in iron.', 'tags': 'PULSES,PROTEIN,ORGANIC'},
                {'name': 'Haricot Beans', 'price': 145.00, 'original_price': 175.00, 'description': 'White beans, great for salads.', 'tags': 'PULSES,PROTEIN,ORGANIC'},
                {'name': 'Butter Beans', 'price': 180.00, 'original_price': 220.00, 'description': 'Large butter beans, creamy texture.', 'tags': 'PULSES,PREMIUM,ORGANIC'},
                {'name': 'Lima Beans', 'price': 160.00, 'original_price': 195.00, 'description': 'Lima beans, high in fiber.', 'tags': 'PULSES,HEALTHY,ORGANIC'},
                {'name': 'Adzuki Beans', 'price': 200.00, 'original_price': 240.00, 'description': 'Red beans for sweets and curries.', 'tags': 'PULSES,PREMIUM,ORGANIC'},
                {'name': 'Horse Gram', 'price': 110.00, 'original_price': 135.00, 'description': 'Kulthi bean, medicinal properties.', 'tags': 'PULSES,MEDICINAL,ORGANIC'},
                {'name': 'Field Beans', 'price': 115.00, 'original_price': 140.00, 'description': 'Val beans, high in protein.', 'tags': 'PULSES,PROTEIN,ORGANIC'},
                {'name': 'Moth Beans', 'price': 125.00, 'original_price': 150.00, 'description': 'Matki beans, drought resistant.', 'tags': 'PULSES,PROTEIN,ORGANIC'},
                {'name': 'Cowpeas', 'price': 118.00, 'original_price': 145.00, 'description': 'Black eyed peas, versatile.', 'tags': 'PULSES,PROTEIN,ORGANIC'},
                {'name': 'Dry Peas', 'price': 95.00, 'original_price': 120.00, 'description': 'Split dry peas, for soups.', 'tags': 'PULSES,PROTEIN,ORGANIC'},
                {'name': 'Lentils Mix', 'price': 130.00, 'original_price': 160.00, 'description': 'Mixed lentils for nutrition.', 'tags': 'PULSES,MIXED,ORGANIC'},
                {'name': 'Chana Dal Split', 'price': 125.00, 'original_price': 155.00, 'description': 'Split chana dal, fine quality.', 'tags': 'PULSES,PROTEIN,ORGANIC'},
                {'name': 'Moong Dal Chilka', 'price': 145.00, 'original_price': 175.00, 'description': 'Green gram with skin, nutritious.', 'tags': 'PULSES,PROTEIN,ORGANIC'},
                {'name': 'Urad Dal Split', 'price': 135.00, 'original_price': 165.00, 'description': 'Split black gram, white variety.', 'tags': 'PULSES,PROTEIN,ORGANIC'},
                {'name': 'Urad Dal Chilka', 'price': 140.00, 'original_price': 170.00, 'description': 'Black gram with skin, earthy taste.', 'tags': 'PULSES,PROTEIN,ORGANIC'},
                {'name': 'Masoor Dal Split', 'price': 112.00, 'original_price': 138.00, 'description': 'Split red lentils, quick cooking.', 'tags': 'PULSES,PROTEIN,ORGANIC'},
                {'name': 'Toor Dal Split', 'price': 152.00, 'original_price': 185.00, 'description': 'Split pigeon peas, premium quality.', 'tags': 'PULSES,STAPLE,ORGANIC'},
                {'name': 'Mixed Dal', 'price': 128.00, 'original_price': 158.00, 'description': 'Assorted dals for daily cooking.', 'tags': 'PULSES,MIXED,ORGANIC'},
                {'name': 'Sabut Masoor', 'price': 118.00, 'original_price': 145.00, 'description': 'Whole brown lentils, rich protein.', 'tags': 'PULSES,PROTEIN,ORGANIC'},
            ],
            'Oilseeds & Oils': [
                {'name': 'Groundnut Oil', 'price': 180.00, 'original_price': 220.00, 'description': 'Cold-pressed groundnut oil, aromatic.', 'tags': 'OIL,COOKING,ORGANIC'},
                {'name': 'Mustard Oil', 'price': 160.00, 'original_price': 200.00, 'description': 'Pure mustard oil, traditional cooking.', 'tags': 'OIL,TRADITIONAL,ORGANIC'},
                {'name': 'Coconut Oil', 'price': 250.00, 'original_price': 300.00, 'description': 'Virgin coconut oil, for cooking and hair.', 'tags': 'OIL,MULTIUSE,ORGANIC'},
                {'name': 'Sesame Oil', 'price': 220.00, 'original_price': 270.00, 'description': 'Premium sesame oil, aromatic.', 'tags': 'OIL,PREMIUM,ORGANIC'},
                {'name': 'Sunflower Oil', 'price': 150.00, 'original_price': 180.00, 'description': 'Refined sunflower oil, light.', 'tags': 'OIL,COOKING,ORGANIC'},
                {'name': 'Olive Oil', 'price': 450.00, 'original_price': 550.00, 'description': 'Extra virgin olive oil, premium.', 'tags': 'OIL,PREMIUM,IMPORTED'},
                {'name': 'Rice Bran Oil', 'price': 170.00, 'original_price': 210.00, 'description': 'Healthy rice bran oil.', 'tags': 'OIL,HEALTHY,ORGANIC'},
                {'name': 'Canola Oil', 'price': 200.00, 'original_price': 240.00, 'description': 'Light canola oil for cooking.', 'tags': 'OIL,COOKING,ORGANIC'},
                {'name': 'Peanut', 'price': 120.00, 'original_price': 150.00, 'description': 'Premium quality peanuts.', 'tags': 'OILSEED,SNACK,ORGANIC'},
                {'name': 'Sesame Seeds', 'price': 150.00, 'original_price': 180.00, 'description': 'White sesame seeds (til).', 'tags': 'OILSEED,COOKING,ORGANIC'},
                {'name': 'Black Sesame', 'price': 180.00, 'original_price': 220.00, 'description': 'Black sesame seeds, medicinal.', 'tags': 'OILSEED,MEDICINAL,ORGANIC'},
                {'name': 'Sunflower Seeds', 'price': 140.00, 'original_price': 170.00, 'description': 'Sunflower seeds for snacking.', 'tags': 'OILSEED,SNACK,ORGANIC'},
                {'name': 'Pumpkin Seeds', 'price': 250.00, 'original_price': 300.00, 'description': 'Roasted pumpkin seeds (pepitas).', 'tags': 'OILSEED,SUPERFOOD,ORGANIC'},
                {'name': 'Chia Seeds', 'price': 300.00, 'original_price': 360.00, 'description': 'Nutritious chia seeds.', 'tags': 'OILSEED,SUPERFOOD,ORGANIC'},
                {'name': 'Flax Seeds', 'price': 180.00, 'original_price': 220.00, 'description': 'Healthy flax seeds (alsi).', 'tags': 'OILSEED,HEALTHY,ORGANIC'},
                {'name': 'Cumin Seeds', 'price': 250.00, 'original_price': 300.00, 'description': 'Premium jeera for cooking.', 'tags': 'SPICES,ESSENTIAL,ORGANIC'},
                {'name': 'Fennel Seeds', 'price': 200.00, 'original_price': 250.00, 'description': 'Saunf for cooking and mouth freshener.', 'tags': 'SPICES,COOKING,ORGANIC'},
                {'name': 'Mustard Seeds', 'price': 120.00, 'original_price': 150.00, 'description': 'Rai for tadka and pickles.', 'tags': 'SPICES,ESSENTIAL,ORGANIC'},
                {'name': 'Coriander Seeds', 'price': 100.00, 'original_price': 125.00, 'description': 'Dhania seeds for cooking.', 'tags': 'SPICES,COOKING,ORGANIC'},
                {'name': 'Fenugreek Seeds', 'price': 110.00, 'original_price': 135.00, 'description': 'Methi seeds for cooking.', 'tags': 'SPICES,MEDICINAL,ORGANIC'},
                {'name': 'Carom Seeds', 'price': 180.00, 'original_price': 220.00, 'description': 'Ajwain for digestion.', 'tags': 'SPICES,MEDICINAL,ORGANIC'},
                {'name': 'Poppy Seeds', 'price': 350.00, 'original_price': 420.00, 'description': 'Khuskhus for sweets.', 'tags': 'SPICES,PREMIUM,ORGANIC'},
                {'name': 'Melon Seeds', 'price': 140.00, 'original_price': 170.00, 'description': 'Magaj seeds for cooking.', 'tags': 'OILSEED,COOKING,ORGANIC'},
                {'name': 'Hemp Seeds', 'price': 280.00, 'original_price': 340.00, 'description': 'Hemp hearts, protein-rich.', 'tags': 'OILSEED,SUPERFOOD,ORGANIC'},
                {'name': 'Almonds', 'price': 450.00, 'original_price': 550.00, 'description': 'Premium almonds (badam).', 'tags': 'NUTS,PREMIUM,ORGANIC'},
                {'name': 'Cashews', 'price': 500.00, 'original_price': 600.00, 'description': 'Raw cashews (kaju).', 'tags': 'NUTS,PREMIUM,ORGANIC'},
                {'name': 'Walnuts', 'price': 550.00, 'original_price': 650.00, 'description': 'Premium walnuts (akhrot).', 'tags': 'NUTS,PREMIUM,ORGANIC'},
                {'name': 'Pistachios', 'price': 600.00, 'original_price': 720.00, 'description': 'Green pistachios (pista).', 'tags': 'NUTS,PREMIUM,ORGANIC'},
                {'name': 'Raisins', 'price': 200.00, 'original_price': 250.00, 'description': 'Golden raisins (kishmish).', 'tags': 'DRY FRUITS,HEALTHY,ORGANIC'},
            ],
            'Spices & Condiments': [
                {'name': 'Turmeric Powder', 'price': 120.00, 'original_price': 150.00, 'description': 'Premium haldi powder, aromatic.', 'tags': 'SPICES,ESSENTIAL,ORGANIC'},
                {'name': 'Red Chili Powder', 'price': 150.00, 'original_price': 180.00, 'description': 'Kashmiri red chili powder, mild.', 'tags': 'SPICES,HOT,ORGANIC'},
                {'name': 'Coriander Powder', 'price': 90.00, 'original_price': 110.00, 'description': 'Fresh dhania powder.', 'tags': 'SPICES,ESSENTIAL,ORGANIC'},
                {'name': 'Cumin Powder', 'price': 180.00, 'original_price': 220.00, 'description': 'Jeera powder for cooking.', 'tags': 'SPICES,ESSENTIAL,ORGANIC'},
                {'name': 'Garam Masala', 'price': 200.00, 'original_price': 250.00, 'description': 'Premium blend for curries.', 'tags': 'SPICES,BLEND,ORGANIC'},
                {'name': 'Black Pepper', 'price': 350.00, 'original_price': 420.00, 'description': 'Whole black pepper (kali mirch).', 'tags': 'SPICES,ESSENTIAL,ORGANIC'},
                {'name': 'Green Cardamom', 'price': 600.00, 'original_price': 720.00, 'description': 'Premium elaichi.', 'tags': 'SPICES,PREMIUM,ORGANIC'},
                {'name': 'Black Cardamom', 'price': 400.00, 'original_price': 480.00, 'description': 'Badi elaichi for biryani.', 'tags': 'SPICES,PREMIUM,ORGANIC'},
                {'name': 'Cinnamon Stick', 'price': 250.00, 'original_price': 300.00, 'description': 'Dalchini for cooking.', 'tags': 'SPICES,COOKING,ORGANIC'},
                {'name': 'Cloves', 'price': 450.00, 'original_price': 550.00, 'description': 'Laung whole.', 'tags': 'SPICES,ESSENTIAL,ORGANIC'},
                {'name': 'Nutmeg', 'price': 300.00, 'original_price': 360.00, 'description': 'Jaiphal whole.', 'tags': 'SPICES,PREMIUM,ORGANIC'},
                {'name': 'Mace', 'price': 350.00, 'original_price': 420.00, 'description': 'Javitri, aril of nutmeg.', 'tags': 'SPICES,PREMIUM,ORGANIC'},
                {'name': 'Saffron', 'price': 15000.00, 'original_price': 18000.00, 'description': 'Kashmiri saffron threads.', 'tags': 'SPICES,PREMIUM,IMPORTED'},
                {'name': 'Asafoetida', 'price': 150.00, 'original_price': 180.00, 'description': 'Hing powder.', 'tags': 'SPICES,ESSENTIAL,ORGANIC'},
                {'name': 'Bay Leaves', 'price': 100.00, 'original_price': 125.00, 'description': 'Tej patta for cooking.', 'tags': 'SPICES,ESSENTIAL,ORGANIC'},
                {'name': 'Dry Ginger', 'price': 180.00, 'original_price': 220.00, 'description': 'Sonth powder.', 'tags': 'SPICES,MEDICINAL,ORGANIC'},
                {'name': 'Tamarind', 'price': 120.00, 'original_price': 150.00, 'description': 'Imli for curries.', 'tags': 'CONDIMENTS,SOUR,ORGANIC'},
                {'name': 'Kokum', 'price': 200.00, 'original_price': 250.00, 'description': 'Kokum for konkani cuisine.', 'tags': 'CONDIMENTS,SOUR,ORGANIC'},
                {'name': 'Raw Mango Powder', 'price': 100.00, 'original_price': 125.00, 'description': 'Amchur powder.', 'tags': 'CONDIMENTS,SOUR,ORGANIC'},
                {'name': 'Amla Powder', 'price': 150.00, 'original_price': 180.00, 'description': 'Dried amla powder.', 'tags': 'CONDIMENTS,HEALTHY,ORGANIC'},
                {'name': 'Pomegranate Seeds', 'price': 180.00, 'original_price': 220.00, 'description': 'Anardana dried seeds.', 'tags': 'CONDIMENTS,SOUR,ORGANIC'},
                {'name': 'Mango Pickle', 'price': 250.00, 'original_price': 300.00, 'description': 'Traditional aam ka achaar.', 'tags': 'PICKLE,TRADITIONAL,ORGANIC'},
                {'name': 'Lemon Pickle', 'price': 200.00, 'original_price': 250.00, 'description': 'Nimbu ka achaar.', 'tags': 'PICKLE,TRADITIONAL,ORGANIC'},
                {'name': 'Mixed Pickle', 'price': 280.00, 'original_price': 340.00, 'description': 'Mixed vegetable achaar.', 'tags': 'PICKLE,TRADITIONAL,ORGANIC'},
                {'name': 'Green Chili Pickle', 'price': 180.00, 'original_price': 220.00, 'description': 'Hari mirchi achaar.', 'tags': 'PICKLE,SPICY,ORGANIC'},
                {'name': 'Ginger Pickle', 'price': 220.00, 'original_price': 270.00, 'description': 'Adrak ka achaar.', 'tags': 'PICKLE,PREMIUM,ORGANIC'},
                {'name': 'Chat Masala', 'price': 120.00, 'original_price': 150.00, 'description': 'Tangy chat masala powder.', 'tags': 'SPICES,BLEND,ORGANIC'},
                {'name': 'Jeera Masala', 'price': 140.00, 'original_price': 170.00, 'description': 'Jeera powder blend.', 'tags': 'SPICES,BLEND,ORGANIC'},
                {'name': 'Pav Bhaji Masala', 'price': 100.00, 'original_price': 125.00, 'description': 'Street food masala.', 'tags': 'SPICES,BLEND,ORGANIC'},
            ],
        }

        # Get all categories
        categories = Category.objects.all()
        
        total_created = 0
        
        for category in categories:
            # Get products data for this category
            category_key = category.name
            if category_key in products_data:
                products_list = products_data[category_key]
                
                # Create products
                for idx, product_data in enumerate(products_list):
                    # Check if product already exists
                    if not Product.objects.filter(name=product_data['name'], category=category).exists():
                        # Use existing image if available, otherwise use first product image
                        existing_image = Product.objects.first()
                        
                        Product.objects.create(
                            name=product_data['name'],
                            category=category,
                            description=product_data['description'],
                            price=product_data['price'],
                            original_price=product_data['original_price'],
                            image=existing_image.image if existing_image else None,
                            rating=round(random.uniform(4.0, 5.0), 1),
                            is_new=idx < 5,
                            is_hot=idx >= 5 and idx < 10,
                            is_sale=idx >= 10 and idx < 15,
                            stock=random.randint(10, 100),
                            view_count=random.randint(10, 500),
                            sold_count=random.randint(5, 200),
                            sku=f"SKU-{category.id:02d}-{idx+1:03d}",
                            tags=product_data['tags'],
                            additional_info='{"origin": "India", "organic": true, "fresh": true}',
                            reviews='[{"name": "Verified Buyer", "date": "2024-01-15", "comment": "Excellent quality!"}]'
                        )
                        total_created += 1
                    else:
                        self.stdout.write(f"Product '{product_data['name']}' already exists in {category.name}")
                self.stdout.write(self.style.SUCCESS(f'Added products to {category.name}'))
        
        self.stdout.write(self.style.SUCCESS(f'Total products created: {total_created}'))
