from django.urls import path
from user import views as user_views

urlpatterns = [
    path('', user_views.index, name='index'),
    path('category/<int:category_id>/', user_views.shop_products, name='category_products'),
    path('about-us/', user_views.about_us, name='about_us'),
    path('portfolio/', user_views.portfolio, name='portfolio'),
    path('portfolio-details/', user_views.portfolio_details, name='portfolio_details'),
    path('shop/', user_views.shop_products, name='shop'),
    path('shop-products/', user_views.shop_products, name='shop_products'),
    path('shop-details/', user_views.shop_details, name='shop_details'),
    path('shop-details/<int:pk>/', user_views.shop_details, name='shop_details'),
    path('submit-review/<int:product_id>/', user_views.submit_review, name='submit_review'),
    path('shop-cart/', user_views.shop_cart, name='shop_cart'),
    path('add-to-cart/', user_views.add_to_cart, name='add_to_cart'),
    path('add-to-wishlist/', user_views.add_to_wishlist, name='add_to_wishlist'),
    path('remove-from-wishlist/<int:wishlist_id>/', user_views.remove_from_wishlist, name='remove_from_wishlist'),
    path('empty-wishlist/', user_views.empty_wishlist, name='empty_wishlist'),
    path('update-cart/', user_views.update_cart, name='update_cart'),
    path('update-cart-ajax/', user_views.update_cart_ajax, name='update_cart_ajax'),
    path('remove-from-cart-ajax/', user_views.remove_from_cart_ajax, name='remove_from_cart_ajax'),
    path('delete-address/<int:address_id>/', user_views.delete_address, name='delete_address'),
    path('remove-from-cart/<int:item_id>/', user_views.remove_from_cart, name='remove_from_cart'),
    path('empty-cart/', user_views.empty_cart, name='empty_cart'),
    path('wishlist/', user_views.wishlist, name='wishlist'),
    path('checkout/', user_views.checkout, name='checkout'),
    path('order-confirmation/<int:order_id>/', user_views.order_confirmation, name='order_confirmation'),
    path('order-tracking/', user_views.order_tracking, name='order_tracking'),
    path('my-account/', user_views.my_account, name='my_account'),
    path('my-account-orders/', user_views.my_account_orders, name='my_account_orders'),
    path('my-account-address/', user_views.my_account_address, name='my_account_address'),
    path('my-account-edit/', user_views.my_account_edit, name='my_account_edit'),
    path('order-details/<int:order_id>/', user_views.order_details, name='order_details'),
    path('print-receipt/<int:order_id>/', user_views.print_receipt, name='print_receipt'),
    path('our-services/', user_views.our_services, name='our_services'),
    path('service-detail/', user_views.service_detail, name='service_detail'),
    path('contact-us/', user_views.contact_us, name='contact_us'),
    path('login/', user_views.login_view, name='login'),
    path('register/', user_views.register_view, name='register'),
    path('logout/', user_views.logout_view, name='logout'),
    path('search/', user_views.search_products, name='search_products'),
    path('razorpay-callback/', user_views.razorpay_callback, name='razorpay_callback'),
]
