# Generated by Django 5.2.10 on 2026-02-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold_count',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='product',
            name='view_count',
            field=models.IntegerField(default=9),
        ),
    ]
