# Generated by Django 5.2.10 on 2026-02-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_product_sold_count_product_stock_product_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default='SKU-0001', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.CharField(default='FOOD,NUTS,ORGANIC', max_length=200),
        ),
    ]
