# Generated by Django 5.2.10 on 2026-02-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_product_sku_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_info',
            field=models.TextField(blank=True, help_text='Enter additional info as JSON: {"key": "value"}', null=True),
        ),
    ]
