# Generated by Django 5.2.10 on 2026-02-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_product_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reviews',
            field=models.TextField(blank=True, help_text='Enter reviews as JSON: [{"name": "Reviewer", "date": "Date", "comment": "Comment"}]', null=True),
        ),
    ]
